# Generated by Django 5.2.1 on 2025-05-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_first_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_last_name',
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_document_number',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(default='Cliente de Prueba', max_length=100),
            preserve_default=False,
        ),
    ]
