# Generated by Django 5.2.1 on 2025-05-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default='2025-05-22'),
            preserve_default=False,
        ),
    ]
